name: sqlite_bloc_rxdart
description: sqlite BLoC rxdart.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  built_value: ^8.0.0
  path_provider: ^2.0.1
  intl: ^0.17.0
  url_launcher: ^6.0.2
  built_collection: ^5.0.0
  collection: ^1.15.0

  disposebag: ^1.5.0-nullsafety.1
  flutter_disposebag: ^1.1.0-nullsafety.1
  distinct_value_connectable_stream: ^1.2.0-nullsafety.5
  sqlbrite: ^2.0.0-nullsafety.0
  flutter_provider: ^2.0.0
  flutter_bloc_pattern: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  built_value_generator: ^8.0.0
  pedantic: ^1.10.0

dependency_overrides:
  analyzer: ^1.1.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
