name: sqlite_bloc_rxdart
description: sqlite BLoC rxdart.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  built_value: ^7.0.8
  path_provider: ^1.6.0
  intl: ^0.16.1
  url_launcher: ^5.4.1

  distinct_value_connectable_stream: ^1.0.3+1
  sqlbrite: ^1.2.0
  flutter_provider: ^1.1.1
  flutter_bloc_pattern: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^7.0.8
  build_runner: ^1.7.3
  pedantic: 1.8.0+1

dependency_overrides:
  pedantic: 1.9.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
